### ISSUE TITLE
关于threadlocal的疑问

### ISSUE THREAD

**Issue by nicky1** [JosephZhu1983/java-common-mistakes#1]
你好，正在学习你的极客时间课程，在第一节中的评论区，和一位同学关于一个问题有不同的理解，
现在不知道他说的对不对，请指教下，谢谢。

![image](https://user-images.githubusercontent.com/6406742/76773836-10c57c80-67de-11ea-9ccc-6f95f6afe142.png)

**Comment by JosephZhu1983** [comment]
值没有清除 + 线程又是复用 导致这个问题
